swagger: "2.0"
info:
  title: STRATUS service
  description: Analytic Services Integration Framework
  contact:
    name: Thomas Maxwell
    email: thomas.maxwell@nasa.gov
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
basePath: /hpda1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /exe:
    get:
      operationId: stat
      description: Returns status information on existing analytics request
      parameters:
        - name: id
          in: query
          description: ID of existing analytics request
          required: true
          type: string
      responses:
        "200":
          description: Status of analytic operation
          schema:
            $ref: '#/definitions/Status'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Executes an analytics request
      operationId: exe
      parameters:
        - in: body
          name: request
          description:  Analytics Request
          required: true
          schema:
            $ref: '#/definitions/Request'
      responses:
        "200":
          description: Analytics request response
          schema:
            $ref: '#/definitions/Status'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Kills a running analytics request
      operationId: kill
      parameters:
        - name: id
          in: query
          description: ID of request to kill
          required: true
          type: string
      responses:
        "200":
          description: request killed
          schema:
            $ref: '#/definitions/Status'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /health:
    get:
      operationId: health
      description: Returns server health information
      responses:
        "200":
          description: Status of analytic operation
          schema:
            $ref: '#/definitions/Health'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /epas:
    get:
      operationId: epas
      description: Returns end point addresses handled by this service
      responses:
        "200":
          description: List of endpoint address specs
          schema:
            type: array
            items:
              $ref: '#/definitions/EPASpec'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:

  Status:
    required:
      - id
      - status
    properties:
      id:
        description: Request Id
        type: string
      status:
        description: Execution status of result
        type: string
      uri:
        description: Result data access uri
        type: string

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  Range:
    required:
    - axis
    properties:
      axis:
        type: string
      start:
        type: string
      end:
        type: string
      slice:
        type: string
      crs:
        type: string

  Domain:
    required:
    - name
    properties:
      name:
        type: string
      bounds:
        type: array
        items:
          $ref: "#/definitions/Range"

  Variable:
    required:
    - name
    - uri
    properties:
      uri:
        type: string
      name:
        type: string
      domain:
        type: string

  Operation:
    required:
    - epa
    - input
    properties:
      input:
        type: string
      epa:
        type: string
      axes:
        type: string
      domain:
        type: string
      groupby:
        type: string
      resample:
        type: string
      select:
        type: string
      args:
        type: string

  Request:
    required:
    - operations
    - domains
    - variables
    properties:
      operations:
        type: array
        items:
          $ref: '#/definitions/Operation'
      domains:
        type: array
        items:
          $ref: '#/definitions/Domain'
      variables:
        type: array
        items:
          $ref: '#/definitions/Variable'

  EPASpec:
    required:
    - epa
    - api
    properties:
      epa:
        type: string
      api:
        type: string

  Health:
    required:
    - status
    properties:
      status:
        type: string


